repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff # linter
        types_or: [python, pyi]
        args: [--fix]
      - id: ruff-format # formatter
        types_or: [python, pyi]
